spring:
  application:
    name: apigateway
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: denunciaservice
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/denuncias/**
  autoconfigure:
    exclude: 
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8081
