server:
      port: 8090

spring:
  application:
    name: servicegateway2

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: denuncia-service
              uri: lb://servicedenuncia
              predicates:
                - Path=/denuncia/**
              filters:
                - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka
